# Generated by Django 4.2 on 2025-11-15 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_contributor_works_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductivityMetrics',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('focus_hours', models.FloatField(default=0.0, help_text='Average weekly focus hours')),
                ('meeting_load', models.FloatField(default=0.0, help_text='Percentage of time in meetings')),
                ('flow_index', models.IntegerField(default=0, help_text='Flow state productivity score (0-100)')),
                ('productivity_peak', models.CharField(blank=True, help_text="Best productivity time (e.g., 'Wednesday mornings')", max_length=100, null=True)),
                ('work_style', models.CharField(blank=True, help_text='Maker vs Manager schedule', max_length=50, null=True)),
                ('well_being_score', models.IntegerField(default=70, help_text='Overall well-being score (0-100)')),
                ('burnout_risk', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='productivity', to='api.contributor')),
            ],
            options={
                'verbose_name_plural': 'Productivity Metrics',
            },
        ),
        migrations.CreateModel(
            name='MockCalendarData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('event_type', models.CharField(choices=[('meeting', 'Meeting'), ('focus', 'Focus Time'), ('break', 'Break')], max_length=50)),
                ('duration_hours', models.FloatField(help_text='Duration in hours')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_events', to='api.contributor')),
            ],
            options={
                'verbose_name_plural': 'Mock Calendar Data',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TeamCollaboration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('interaction_count', models.IntegerField(default=0, help_text='Number of interactions')),
                ('interaction_type', models.CharField(help_text='Type of interaction (pr_review, issue_mention, etc.)', max_length=50)),
                ('last_interaction', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contributor_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_from', to='api.contributor')),
                ('contributor_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collaborations_to', to='api.contributor')),
            ],
            options={
                'verbose_name_plural': 'Team Collaborations',
                'unique_together': {('contributor_a', 'contributor_b', 'interaction_type')},
            },
        ),
    ]
